name: Github Actions Debug

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: action/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v4.0.0